server:
  port: 8082

spring:
  application:
    name: reservation-service
  r2dbc:
    username: root
    password: Tmdwns0624@
    url: r2dbc:mysql://localhost:3306/petclinic_reservations
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  cloud:
    function:
      definition: dispatchReservation
    stream:
      bindings:
        dispatchReservation-in-0:
          destination: reservation-dispatched
          group: ${spring.application.name}

        acceptReservation-out-0:
          destination: reservation-accepted # 큐의 이름
      rabbit: # 스프링 클라우드 스트림 바인딩에 대한 RabbitMQ 설정
        bindings:
          acceptReservation-out-0:
            producer:
              transacted: true # 트랜잭션 지원 활성화
        rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest
          connection-timeout: 5s
      

