server:
  port: 8082

spring:
  application:
    name: reservation-service
  r2dbc:
    username: root
    password: Tmdwns0624@
    url: r2dbc:mysql://localhost:3306/petclinic_reservations
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
